 version: "3.8"

 services:
    snowflake-proxy:
        network_mode: host
        image: thetorproject/snowflake-proxy:latest
        #image: mdellabitta/snowflake-proxy:latest
        container_name: snowflake-proxy
        restart: unless-stopped
