version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: "${PIHOLE_PASSWORD}"
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  unifi:
    image: ryansch/unifi-rpi:latest
    container_name: unifi
    restart: unless-stopped
    network_mode: host
    # Uncomment the following to set java options
    # environment:
    #   JAVA_OPTS: -Xmx512M
    volumes:
      # Unifi v5.0.7 creates all of these directories (some remain empty)
      - unifi-config:/var/lib/unifi
      - unifi-log:/usr/lib/unifi/logs
      - unifi-log2:/var/log/unifi
      - unifi-run:/usr/lib/unifi/run
      - unifi-run2:/run/unifi
      - unifi-work:/usr/lib/unifi/work
    environment:
      - PUID=1000
      - PGID=1000
volumes:
  unifi-config:
  unifi-log:
  unifi-log2:
  unifi-run:
  unifi-run2:
  unifi-work:
  
