---
- hosts: pis
  become: yes
  gather_facts: no
  tasks:

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ pi_hostname }}"

    - name: Add docker apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

    - name: Add docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu focal stable
        
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
    
    - name: Install packages
      apt:
        name: "{{item}}"
        state: latest
      loop:
        - avahi-daemon
        - libnss-mdns
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - python3-pip
        
    - name: Install docker-compose
      pip:
        name: docker-compose
        state: latest
            
    - name: Get rid of motd-news adware
      copy:
        content: "ENABLED=0"
        dest: /etc/default/motd-news
        owner: root
        group: root
        mode: u=rw,g=r,o=r
        
    - name: Disable spammy motd bits
      file: dest="{{item}}" mode=a-x
      loop:
        - /etc/update-motd.d/10-help-text 
        - /etc/update-motd.d/50-motd-news

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

