version: "3"

networks:
  dns_net:
    driver: bridge
    ipam:
        config:
        - subnet: 172.20.0.0/16

services:

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      dns_net:
        ipv4_address: 172.20.0.6
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: "${PIHOLE_PASSWORD}"
      PIHOLE_DNS_: 172.20.0.7
    volumes:
      - etc-pihole:/etc/pihole/
      - etc-dnsmasq.d:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  unbound:
    container_name: unbound
    build: unbound
    networks:
      dns_net:
        ipv4_address: 172.20.0.7
    ports:
      - "5335:5335/udp"
      - "5335:5335/tcp"
    restart: unless-stopped

volumes:
  etc-pihole:
  etc-dnsmasq.d:

