---
version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/homeassistant:/config
    #devices:
      #- /path/to/device:/path/to/device #optional
    restart: unless-stopped
