---
version: "2.1"
services:
  
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - unifi_config:/config
    ports:
      - 3478:3478/udp #stun
      - 10001:10001/udp #device discovery
      - 8080:8080

    networks:
      - traefik_public
      
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.unifi.entrypoints=websecure"
      - "traefik.http.routers.unifi.tls=true"
      - "traefik.http.routers.unifi.tls.certResolver=leresolver"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      
volumes:
  unifi_config:

networks:
  traefik_public:
    external: true
