---
- hosts: pis
  become: yes
  gather_facts: no
  tasks:

    # Fix ubuntu's DNS situation so we get port 53 back
    
    - name: Disable DNSStubListener
      community.general.ini_file:
        path: /etc/systemd/resolved.conf
        section: Resolve
        option: DNSStubListener
        value: "no"
        
    - name: Restart resolved.service
      ansible.builtin.systemd:
        state: restarted
        name: systemd-resolved.service

    - name: Check if resolvd.conf exists
      stat:
        path: "{{ item }}"
      with_items:
        - /etc/resolv.conf
      register: check_file_name

    - name: Move resolvd.conf to resolvd.conf.bak
      command: mv "{{ item.stat.path }}" "{{destpath}}"
      with_items:
        - "{{ check_file_name.results }}"
      when: item.stat.exists == true and not item.stat.islnk
        
    - name: Link systemd resolvd.conf
      file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link