---
- hosts: localhost
  become: yes
  gather_facts: no
  tasks:

    # - name: Set network config
    #   copy:
    #     content: |
    #       network:
    #         version: 2
    #         ethernets:
    #           eth0:
    #             addresses: [192.168.88.2/24]
    #             gateway4: 192.168.88.1
    #             nameservers:
    #               addresses: [1.0.0.2,1.1.1.2]
    #             dhcp4: no
    #     dest: /etc/netplan/50-cloud-init.yaml
          
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ pi_hostname }}"

    - name: Edit hostname into hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 localhost {{ pi_hostname }} {{ pi_hostname }}.local"
        state: present
        regexp: '^127\.0\.0\.1'

    - name: Set time zone
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "TZ=\"{{ tz }}\""      

    # - name: Set swap_file and swap_space variables
    #   ansible.builtin.set_fact:
    #     swap_space: 2147483648
    #     swap_file: /mnt/swapfile

    # - name: Check if swap file exists
    #   ansible.builtin.stat:
    #     path: "{{ swap_file }}"
    #   register: swap_file_check

    # - name: Create swap file
    #   command:
    #     cmd: "fallocate -l {{ swap_space }} {{ swap_file }}"
    #   when: not swap_file_check.stat.exists

    # - name: Set permissions on swap file
    #   ansible.builtin.file:
    #     path: "{{ swap_file }}"
    #     mode: 0600

    # - name: Format swap file
    #   command:
    #     cmd: "mkswap {{ swap_file }}"
    #   when: not swap_file_check.stat.exists

    # - name: Add to fstab
    #   ansible.builtin.lineinfile:
    #     dest: /etc/fstab
    #     regexp: "{{ swap_file }}"
    #     line: "{{ swap_file }} none swap sw 0 0"

    # - name: Turn on swap
    #   command:
    #     cmd: "swapon -a"
    #   when: not swap_file_check.stat.exists
        
    - name: Add docker apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg #todo change to raspbian
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

    - name: Add docker repository
      ansible.builtin.apt_repository:
        update_cache: no
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable

    - name: Add netdata apt key
      ansible.builtin.apt_key:
        url: https://packagecloud.io/netdata/netdata/gpgkey 
        id: 54832F89F09FED90

    - name: Add netdata repository
      ansible.builtin.apt_repository:
        update_cache: no
        repo: deb [arch=amd64] https://packagecloud.io/netdata/netdata/debian/ buster main
        
    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Upgrade all apt packages
      apt:
        upgrade: dist
        force_apt_get: yes
    
    - name: Install packages
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - apt-transport-https
          - avahi-daemon
          - libnss-mdns
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - python3-pip
          - netdata
          - haveged
          - powertop
          # - libraspberrypi-bin
        state: latest
        
    - name: Install docker-compose
      pip:
        name: docker-compose
        state: latest

    - name: Add pi user to docker group
      user:
        name: pi
        groups: docker
        append: yes

    - name: Configure PowerTOP auto tune
      copy:
        content: |
          [Unit]
          Description=PowerTOP auto tune

          [Service]
          Type=oneshot
          ExecStart=/usr/sbin/powertop --auto-tune

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/powertop.service

    - name: Install PowerTOP auto tune
      ansible.builtin.systemd:
        state: started
        enabled: yes
        name: powertop.service
      
    # - name: Configure pi bootstrap parameters
    #   copy:
    #     content: |
    #       enable_uart=0
    #       dtparam=audio=off
    #       dtparam=i2c_arm=off
    #       dtparam=spi=off
    #       gpu_mem=16
    #       dtoverlay=disable-bt
    #       dtoverlay=disable-wifi
    #     dest: /boot/firmware/usercfg.txt

    # - name: Set up kernel for docker
    #   copy:
    #     content: |
    #       swapaccount=1 cgroup_enable=memory cgroup_memory=1 dwc_otg.fiq_fix_enable=1 net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc
    #     dest: /boot/firmware/cmdline.txt

    # - name: Disable wifi
    #   command:
    #     cmd: systemctl mask wpa_supplicant.service
