---
- hosts: localhost
  become: yes

  tasks:
    - set_fact:
        deb_arch: "{{ 'armhf' if ( ansible_facts['architecture'] == 'armv7l' ) else 'amd64' }}"

    - set_fact:
        deb_os: "{{ 'raspbian' if ( ansible_facts['lsb']['id'] == 'Raspbian' ) else 'debian' }}"

    - set_fact:
        deb_codename: "{{ ansible_facts['lsb']['codename'] }}"

    - name: Set network config
      copy:
        content: |
          static ip_address={{ ip_address }}/24
          static routers={{ router }}
          static domain_name_servers={{ domain_name_servers }}
        dest: /etc/dhcpcd.conf
      when: deb_os == "raspbian"

    - name: Set hostname
      script:
        cmd: "/usr/bin/raspi-config nonint do_hostname {{ pi_hostname }}"
      when: deb_os == "raspbian"

    - name: Set locale
      script:
        cmd: "/usr/bin/raspi-config nonint do_change_timezone {{ tz }}"
      when: deb_os == "raspbian"

    - name: Set timezone
      script:
        cmd: "/usr/bin/raspi-config nonint do_change_locale {{ locale }}"
      when: deb_os == "raspbian"

    - name: Set wifi country
      script:
        cmd: "/usr/bin/raspi-config nonint do_wifi_country {{ wifi }}"
      when: deb_os == "raspbian"

    - name: Set memory split
      script:
        cmd: "/usr/bin/raspi-config nonint do_memory_split {{ gpu_mem }}"
      when: deb_os == "raspbian"

    - name: Configure swap
      ansible.builtin.lineinfile:
        path: /etc/dphys-swapfile
        line: CONF_SWAPSIZE=2048
        state: present
        regexp: '^CONF_SWAPSIZE'
      when: deb_os == "raspbian"
      notify:
      - Refresh swap

    - name: Add docker apt key
      ansible.builtin.shell:
        cmd: "curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/docker-ce-archive-keyring.gpg > /dev/null"
        creates: /usr/share/keyrings/docker-ce-archive-keyring.gpg

    - name: Add docker repository
      ansible.builtin.apt_repository:
        update_cache: no
        filename: docker-ce
        repo: "deb [arch={{ deb_arch }} signed-by=/usr/share/keyrings/docker-ce-archive-keyring.gpg] https://download.docker.com/linux/{{ deb_os }} {{ deb_codename }} stable"

    - name: Add netdata apt key
      ansible.builtin.shell:
        cmd: "curl -fsSL https://packagecloud.io/netdata/netdata/gpgkey | gpg --dearmor | sudo tee /usr/share/keyrings/netdata-archive-keyring.gpg > /dev/null"
        creates: /usr/share/keyrings/netdata-archive-keyring.gpg

    - name: Add netdata repository
      ansible.builtin.apt_repository:
        update_cache: no
        filename: netdata
        # netdata doesn't have an explicit raspbian release so defaulting to debian
        repo: "deb [arch={{ deb_arch }} signed-by=/usr/share/keyrings/netdata-archive-keyring.gpg] https://packagecloud.io/netdata/netdata/debian {{ deb_codename }} main"

    - name: Prevent packages.microsoft.com from resolving
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: 0.0.0.0 packages.microsoft.com
        state: present
        regexp: 'packages.microsoft.com$'
    
    - name: Untrust Microsoft key
      copy:
        content: ""
        dest: /etc/apt/trusted.gpg.d/microsoft.gpg 

    - name: Remove VSCode package source
      copy:
        content: ""
        dest: /etc/apt/sources.list.d/vscode.list

    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Upgrade all apt packages
      apt:
        upgrade: dist
        force_apt_get: yes
        
    - name: Install packages
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - apt-transport-https
          - avahi-daemon
          - libnss-mdns
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - python3-pip
          - netdata
          - haveged
          - powertop
        state: latest

    - name: Install docker-compose
      pip:
        name: docker-compose
        state: latest

    - name: Add pi user to docker group
      user:
        name: pi
        groups: docker
        append: yes

    - name: Configure PowerTOP auto tune
      copy:
        content: |
          [Unit]
          Description=PowerTOP auto tune

          [Service]
          Type=oneshot
          ExecStart=/usr/sbin/powertop --auto-tune

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/powertop.service

    - name: Install PowerTOP auto tune
      ansible.builtin.systemd:
        state: started
        enabled: yes
        name: powertop.service

  handlers:
    - name: Reload swap
      shell: "{{ item }}"
      with_items:
      - dphys-swapfile swapoff
      - dphys-swapfile setup
      - dphys-swapfile swapon
