Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: "venv/"
  config.vm.provision "shell",
    inline: "sudo apt-get install -y python3-distutils python3-apt"
  config.vm.provision :ansible_local do |ansible|
    ansible.limit = 'all,localhost'
    ansible.become = true
    ansible.install = true
    ansible.install_mode = "pip"
    ansible.pip_install_cmd = "curl -s https://bootstrap.pypa.io/get-pip.py | sudo  python3"
    ansible.version = "latest"
    ansible.galaxy_command = "sudo ansible-galaxy collection install -r=%{role_file} --collections-path=/usr/share/ansible/collections --force"
    ansible.galaxy_role_file = "requirements.yml"
    ansible.playbook = "system-setup.yml"
    ansible.extra_vars = {
      pi_hostname: "pi",
      tz: "America/New_York"
    }
  end
end
