Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: "venv/"
  config.vm.provision "shell" do |shell|
    shell.path = "../bootstrap.sh"
    shell.privileged = false
  end
end
