---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - USER=admin
      - PASS="b!rEms9Gkoq&%t3pdFY5QiHK"
    volumes:
      - config:/config
      - /var/transmission/downloads:/downloads
      - /var/transmission/watch:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"      
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
      
volumes:
  config:
